version: 0.2
phases:
  install:
    commands:
    # Download and Install python for aws cli
    - wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz
    - tar xJf Python-3.6.0.tar.xz
    - cd Python-3.6.0
    - ./configure
    - make
    - make install
    # Download and upgrade aws cli
    - pip3 install --upgrade awscli
    - wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
    - chmod +x ./jq
    - cp jq /usr/bin
    - cp ${CODEBUILD_SRC_DIR}/src/environments/environment.ts ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts
    # Get parameters aws and set variables
    # Replace variable whit sed command in environment file
    - sed -i "s;__ENDPOINT_PUBLICA__;${BUILD_ENDPOINT_API_PUBLICA};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts
    - sed -i "s;__ENDPOINT_PRIVADA__;${BUILD_ENDPOINT_API_PRIVADA};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts
    - sed -i "s;__ENDPOINT_ROLES__;${BUILD_ENDPOINT_API_ROLES};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts
    - sed -i "s;__ENDPOINT_ELASTICSEARCH__;${BUILD_ENDPOINT_API_ELASTICSEARCH};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts

    - sed -i "s;__COGNITO_URL_AUTHORIZE__;${BUILD_COGNITO_URL_AUTHORIZE};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts

    - sed -i "s;__COGNITO_LOGOUT_URL__;${BUILD_COGNITO_LOGOUT_URL};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts

    - sed -i "s;__COGNITO_CLIENT_ID_1__;${BUILD_COGNITO_CLIENT_ID_1};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts

    - sed -i "s;__COGNITO_CLIENT_REDIRECT_URI_1__;${BUILD_COGNITO_CLIENT_REDIRECT_URI_1};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts

    - sed -i "s;__COGNITO_CLIENT_LOGOUT_URI_1__;${BUILD_COGNITO_CLIENT_LOGOUT_URI_1};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts

    - sed -i "s;__COGNITO_CLIENT_ID_2__;${BUILD_COGNITO_CLIENT_ID_2};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts

    - sed -i "s;__COGNITO_CLIENT_REDIRECT_URI_2__;${BUILD_COGNITO_CLIENT_REDIRECT_URI_2};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts

    - sed -i "s;__COGNITO_CLIENT_LOGOUT_URI_2__;${BUILD_COGNITO_CLIENT_LOGOUT_URI_2};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts

    # Download and Install NodeJS 8.0
    - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    - echo Installing source NPM dependencies...
    # Install http drivers for node
    - sudo apt-get update -y
    - sudo apt-get install -y apt-transport-https
    # Install Yarn Package Manager
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update -y
    - sudo apt-get install -y yarn
    - yarn global add @angular/cli@6.0.8
    - yarn install
    - yarn add ngx-spinner

  build:
    commands:
    # Builds Angular application. You can also build using custom environment here like mock or staging
    - echo Build started on `date`
    - cd ${CODEBUILD_SRC_DIR}
    - echo file environment angular
    - more ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts
    - ng build --prod

  post_build:
    commands:
    # Clear S3 bucket.
    - aws s3 rm s3://${S3_BUCKET} --recursive
    - echo S3 bucket is cleared.
    # Copy dist folder to S3 bucket, As of Angular 6, builds are stored inside an app folder in distribution and not at the root of the dist folder
    - aws s3 cp dist s3://${S3_BUCKET} --recursive --acl public-read
    - echo Build completed on `date`

artifacts:
  files:
  - '**/*'
  discard-paths: yes
  base-directory: 'dist*'
