version: 0.2
phases:
  install:
    commands:
    - rm -f ${CODEBUILD_SRC_DIR}/src/environments/environment.ts
    - touch ${CODEBUILD_SRC_DIR}/src/environments/environment.ts
    - cp ${CODEBUILD_SRC_DIR}/src/environments/environment.sample.ts ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts

    # Replace variable whit sed command in environment file
    - sed -i "s;BUILD_BOTON_PAGO_TGR_URL;${BUILD_BOTON_PAGO_TGR_URL};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts
    - sed -i "s;BUILD_BACK_ENDPOINT;${BUILD_BACK_ENDPOINT};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts
    - sed -i "s;BUILD_ELASTICSEARCH_ENDPOINT;${BUILD_ELASTICSEARCH_ENDPOINT};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts
    - sed -i "s;BUILD_AUTHORIZE_URL;${BUILD_AUTHORIZE_URL};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts
    - sed -i "s;BUILD_LOGOUT_URL;${BUILD_LOGOUT_URL};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts
    - sed -i "s;BUILD_CLIENT_ID;${BUILD_CLIENT_ID};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts
    - sed -i "s;BUILD_REDIRECT_URI;${BUILD_REDIRECT_URI};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts
    - sed -i "s;BUILD_LOGOUT_URI;${BUILD_LOGOUT_URI};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts
    - sed -i "s;BUILD_CUENTA_USUARIO_URL;${BUILD_CUENTA_USUARIO_URL};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts
    - sed -i "s;BUILD_RECAPTCHA_KEY_V3;${BUILD_RECAPTCHA_KEY_V3};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts
    - sed -i "s;BUILD_RECAPTCHA_KEY_V2;${BUILD_RECAPTCHA_KEY_V2};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts
    - sed -i "s;BUILD_DEVICE_INFO_ENDPOINT;${BUILD_DEVICE_INFO_ENDPOINT};g" ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts

    - npm install
    - npm install -g @angular/cli@6.0.8

  build:
    commands:
    # Builds Angular application. You can also build using custom environment here like mock or staging
    - echo Build started on `date`
    - cd ${CODEBUILD_SRC_DIR}
    - echo file environment angular
    - more ${CODEBUILD_SRC_DIR}/src/environments/environment.prod.ts
    - ng build --prod

  post_build:
    commands:
    # Clear S3 bucket.
    - aws s3 rm s3://${S3_BUCKET} --recursive
    - echo S3 bucket is cleared.
    # Copy dist folder to S3 bucket, As of Angular 6, builds are stored inside an app folder in distribution and not at the root of the dist folder
    - aws s3 cp dist/tgr-contribuciones-frontend s3://${S3_BUCKET} --recursive --acl public-read
    - echo Build completed on `date`

artifacts:
  files:
  - '**/*'
  discard-paths: yes
  base-directory: 'dist*'
